# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2
import type_pb2 as type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61ttle.proto\x12\nmsg.battle\x1a\nbase.proto\x1a\ntype.proto\"=\n\x11\x42\x61ttleJoinRequest\x12\x0e\n\x06roleid\x18\x01 \x01(\x04\x12\r\n\x05token\x18\x02 \x01(\t:\t\x88\xb5\x18\x81$\x80\xa6\x1d\x0c\"I\n\x15\x42\x61ttleProgressMessage\x12\x0e\n\x06roleid\x18\x01 \x01(\x04\x12\x10\n\x08progress\x18\x02 \x01(\x05:\x0e\x88\xb5\x18\x82$\x80\xa6\x1d\x0c\x90\xb5\x18\x82$\".\n\x12\x42\x61ttleReadyRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x05:\t\x88\xb5\x18\x83$\x80\xa6\x1d\x0c\"\x1a\n\x11\x42\x61ttleStartNotify:\x05\x88\xb5\x18\x84$\"A\n\x13\x42\x61ttleReportRequest\x12\x1f\n\x05order\x18\x01 \x01(\x0b\x32\x10.msg.BattleOrder:\t\x88\xb5\x18\x85$\x80\xa6\x1d\x0c\"[\n\x10\x42\x61ttleSyncNotify\x12\r\n\x05\x66rame\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12#\n\tframelist\x18\x03 \x03(\x0b\x32\x10.msg.BattleFrame:\x05\x88\xb5\x18\x86$\"\x81\x01\n\x11\x42\x61ttleQuitRequest\x12!\n\x06result\x18\x01 \x01(\x0e\x32\x11.msg.BattleResult\x12\x13\n\x0bsvnrevision\x18\x02 \x01(\x05\x12\x14\n\x0c\x65xcelversion\x18\x03 \x01(\x05\x12\x0e\n\x06reason\x18\x04 \x01(\x05:\x0e\x88\xb5\x18\x87$\x80\xa6\x1d\x0c\x90\xb5\x18\x88$\"b\n\x12\x42\x61ttleQuitResponse\x12\x0e\n\x06roleid\x18\x01 \x01(\x04\x12!\n\x06result\x18\x02 \x01(\x0e\x32\x11.msg.BattleResult\x12\x0e\n\x06reason\x18\x03 \x01(\x05:\t\x88\xb5\x18\x88$\x80\xa6\x1d\x0c*\x82\x02\n\x0f\x45rrorcodeBattle\x12\x0b\n\x07Success\x10\x00\x12\x19\n\x13\x42\x61ttleJoinNotInArea\x10\x81\x82H\x12\x1c\n\x16\x42\x61ttleJoinInvalidToken\x10\x82\x82H\x12\x1d\n\x17\x42\x61ttleProgressNotInArea\x10\x81\x84H\x12\x1a\n\x14\x42\x61ttleReadyNotInArea\x10\x81\x86H\x12\x1b\n\x15\x42\x61ttleReportNotInArea\x10\x81\x8aH\x12\x1b\n\x15\x42\x61ttleReportIsFighter\x10\x82\x8aH\x12\x19\n\x13\x42\x61ttleQuitNotInArea\x10\x81\x8eH\x12\x19\n\x13\x42\x61ttleQuitIsFighter\x10\x82\x8eHb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATTLEJOINREQUEST._options = None
  _BATTLEJOINREQUEST._serialized_options = b'\210\265\030\201$\200\246\035\014'
  _BATTLEPROGRESSMESSAGE._options = None
  _BATTLEPROGRESSMESSAGE._serialized_options = b'\210\265\030\202$\200\246\035\014\220\265\030\202$'
  _BATTLEREADYREQUEST._options = None
  _BATTLEREADYREQUEST._serialized_options = b'\210\265\030\203$\200\246\035\014'
  _BATTLESTARTNOTIFY._options = None
  _BATTLESTARTNOTIFY._serialized_options = b'\210\265\030\204$'
  _BATTLEREPORTREQUEST._options = None
  _BATTLEREPORTREQUEST._serialized_options = b'\210\265\030\205$\200\246\035\014'
  _BATTLESYNCNOTIFY._options = None
  _BATTLESYNCNOTIFY._serialized_options = b'\210\265\030\206$'
  _BATTLEQUITREQUEST._options = None
  _BATTLEQUITREQUEST._serialized_options = b'\210\265\030\207$\200\246\035\014\220\265\030\210$'
  _BATTLEQUITRESPONSE._options = None
  _BATTLEQUITRESPONSE._serialized_options = b'\210\265\030\210$\200\246\035\014'
  _ERRORCODEBATTLE._serialized_start=659
  _ERRORCODEBATTLE._serialized_end=917
  _BATTLEJOINREQUEST._serialized_start=52
  _BATTLEJOINREQUEST._serialized_end=113
  _BATTLEPROGRESSMESSAGE._serialized_start=115
  _BATTLEPROGRESSMESSAGE._serialized_end=188
  _BATTLEREADYREQUEST._serialized_start=190
  _BATTLEREADYREQUEST._serialized_end=236
  _BATTLESTARTNOTIFY._serialized_start=238
  _BATTLESTARTNOTIFY._serialized_end=264
  _BATTLEREPORTREQUEST._serialized_start=266
  _BATTLEREPORTREQUEST._serialized_end=331
  _BATTLESYNCNOTIFY._serialized_start=333
  _BATTLESYNCNOTIFY._serialized_end=424
  _BATTLEQUITREQUEST._serialized_start=427
  _BATTLEQUITREQUEST._serialized_end=556
  _BATTLEQUITRESPONSE._serialized_start=558
  _BATTLEQUITRESPONSE._serialized_end=656
# @@protoc_insertion_point(module_scope)
