# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: herotype.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eherotype.proto\x12\x08msg.hero\x1a\nbase.proto\"\x82\x01\n\x08HeroInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x62\x61seid\x18\x02 \x01(\x05\x12\r\n\x05level\x18\x03 \x01(\x05\x12\r\n\x05grade\x18\x04 \x01(\x05\x12\x0f\n\x07quality\x18\x05 \x01(\x05\x12\x0f\n\x07locking\x18\x06 \x01(\x08\x12\x1a\n\x06skills\x18\x07 \x03(\x0b\x32\n.msg.Skillb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'herotype_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEROINFO._serialized_start=41
  _HEROINFO._serialized_end=171
# @@protoc_insertion_point(module_scope)
