# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mailtype.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emailtype.proto\x12\x08msg.mail\x1a\nbase.proto\"\x9c\x02\n\x0eMailDetailInfo\x12\x0b\n\x03mid\x18\x01 \x01(\x04\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.msg.mail.MailType\x12\x0b\n\x03tid\x18\x03 \x01(\r\x12\"\n\x05state\x18\x04 \x01(\x0e\x32\x13.msg.mail.MailState\x12\x0b\n\x03tag\x18\x05 \x01(\r\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x12\x10\n\x08keepdays\x18\x07 \x01(\x05\x12\x0e\n\x06sender\x18\x08 \x01(\x04\x12\x12\n\nsendername\x18\t \x01(\t\x12\r\n\x05title\x18\n \x01(\t\x12\x0f\n\x07\x63ontent\x18\x0b \x01(\t\x12\x11\n\tparamlist\x18\x0c \x01(\t\x12!\n\nattachment\x18\r \x03(\x0b\x32\r.msg.Resource*b\n\x08MailType\x12\x12\n\x0e\x65MailType_None\x10\x00\x12\x12\n\x0e\x65MailType_User\x10\x01\x12\x14\n\x10\x65MailType_System\x10\x02\x12\x18\n\x14\x65MailType_GameMaster\x10\x03*}\n\tMailState\x12\x13\n\x0f\x65MailState_None\x10\x00\x12\x15\n\x11\x65MailState_Unread\x10\x01\x12\x15\n\x11\x65MailState_Readed\x10\x02\x12\x15\n\x11\x65MailState_Drawed\x10\x03\x12\x16\n\x12\x65MailState_Deleted\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mailtype_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAILTYPE._serialized_start=327
  _MAILTYPE._serialized_end=425
  _MAILSTATE._serialized_start=427
  _MAILSTATE._serialized_end=552
  _MAILDETAILINFO._serialized_start=41
  _MAILDETAILINFO._serialized_end=325
# @@protoc_insertion_point(module_scope)
