# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import type_pb2 as type__pb2
import mailtype_pb2 as mailtype__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmail.proto\x12\x08msg.mail\x1a\ntype.proto\x1a\x0emailtype.proto\"?\n\x0fGetInBoxRequest\x12\r\n\x05index\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r:\x0e\x88\xb5\x18\x81,\x90\xb5\x18\x82,\x80\xa6\x1d\x02\"b\n\x10GetInBoxResponse\x12\r\n\x05index\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12)\n\x07mailbox\x18\x03 \x03(\x0b\x32\x18.msg.mail.MailDetailInfo:\x05\x88\xb5\x18\x82,\"Q\n\rNewMailNotify\x12\x0e\n\x06mailid\x18\x01 \x01(\x04\x12)\n\x07newmail\x18\x02 \x01(\x0b\x32\x18.msg.mail.MailDetailInfo:\x05\x88\xb5\x18\x83,\"1\n\x0fReadMailRequest\x12\x0e\n\x06mailid\x18\x01 \x01(\x04:\x0e\x88\xb5\x18\x84,\x90\xb5\x18\x85,\x80\xa6\x1d\x02\"M\n\x10ReadMailResponse\x12\x0e\n\x06mailid\x18\x01 \x01(\x04\x12\"\n\x05state\x18\x02 \x01(\x0e\x32\x13.msg.mail.MailState:\x05\x88\xb5\x18\x85,\"7\n\x14GotAttachmentRequest\x12\x0f\n\x07mailids\x18\x01 \x03(\x04:\x0e\x88\xb5\x18\x86,\x90\xb5\x18\x87,\x80\xa6\x1d\x02\"\x9c\x01\n\x15GotAttachmentResponse\x12<\n\nstatuslist\x18\x01 \x03(\x0b\x32(.msg.mail.GotAttachmentResponse.MailUnit\x1a>\n\x08MailUnit\x12\x0e\n\x06mailid\x18\x01 \x01(\x04\x12\"\n\x05state\x18\x02 \x01(\x0e\x32\x13.msg.mail.MailState:\x05\x88\xb5\x18\x87,\"4\n\x11RemoveMailRequest\x12\x0f\n\x07mailids\x18\x01 \x03(\x04:\x0e\x88\xb5\x18\x88,\x90\xb5\x18\x89,\x80\xa6\x1d\x02\",\n\x12RemoveMailResponse\x12\x0f\n\x07mailids\x18\x01 \x03(\x04:\x05\x88\xb5\x18\x89,*\xd5\x01\n\rErrorcodeMail\x12\x0b\n\x07Success\x10\x00\x12\x17\n\x11ReadMailIDInvalid\x10\x81\x88X\x12\x1b\n\x15ReadMailStatusInvalid\x10\x82\x88X\x12\x1b\n\x15\x44rawMailStatusInvalid\x10\x81\x8cX\x12\x17\n\x11\x44rawMailBagIsFull\x10\x82\x8cX\x12\x17\n\x11\x44rawMailIDInvalid\x10\x83\x8cX\x12\x19\n\x13RemoveMailIDInvalid\x10\x81\x90X\x12\x17\n\x11YouMustDrawedMail\x10\x82\x90Xb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mail_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETINBOXREQUEST._options = None
  _GETINBOXREQUEST._serialized_options = b'\210\265\030\201,\220\265\030\202,\200\246\035\002'
  _GETINBOXRESPONSE._options = None
  _GETINBOXRESPONSE._serialized_options = b'\210\265\030\202,'
  _NEWMAILNOTIFY._options = None
  _NEWMAILNOTIFY._serialized_options = b'\210\265\030\203,'
  _READMAILREQUEST._options = None
  _READMAILREQUEST._serialized_options = b'\210\265\030\204,\220\265\030\205,\200\246\035\002'
  _READMAILRESPONSE._options = None
  _READMAILRESPONSE._serialized_options = b'\210\265\030\205,'
  _GOTATTACHMENTREQUEST._options = None
  _GOTATTACHMENTREQUEST._serialized_options = b'\210\265\030\206,\220\265\030\207,\200\246\035\002'
  _GOTATTACHMENTRESPONSE._options = None
  _GOTATTACHMENTRESPONSE._serialized_options = b'\210\265\030\207,'
  _REMOVEMAILREQUEST._options = None
  _REMOVEMAILREQUEST._serialized_options = b'\210\265\030\210,\220\265\030\211,\200\246\035\002'
  _REMOVEMAILRESPONSE._options = None
  _REMOVEMAILRESPONSE._serialized_options = b'\210\265\030\211,'
  _ERRORCODEMAIL._serialized_start=747
  _ERRORCODEMAIL._serialized_end=960
  _GETINBOXREQUEST._serialized_start=52
  _GETINBOXREQUEST._serialized_end=115
  _GETINBOXRESPONSE._serialized_start=117
  _GETINBOXRESPONSE._serialized_end=215
  _NEWMAILNOTIFY._serialized_start=217
  _NEWMAILNOTIFY._serialized_end=298
  _READMAILREQUEST._serialized_start=300
  _READMAILREQUEST._serialized_end=349
  _READMAILRESPONSE._serialized_start=351
  _READMAILRESPONSE._serialized_end=428
  _GOTATTACHMENTREQUEST._serialized_start=430
  _GOTATTACHMENTREQUEST._serialized_end=485
  _GOTATTACHMENTRESPONSE._serialized_start=488
  _GOTATTACHMENTRESPONSE._serialized_end=644
  _GOTATTACHMENTRESPONSE_MAILUNIT._serialized_start=575
  _GOTATTACHMENTRESPONSE_MAILUNIT._serialized_end=637
  _REMOVEMAILREQUEST._serialized_start=646
  _REMOVEMAILREQUEST._serialized_end=698
  _REMOVEMAILRESPONSE._serialized_start=700
  _REMOVEMAILRESPONSE._serialized_end=744
# @@protoc_insertion_point(module_scope)
