# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roletype.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eroletype.proto\x12\x08msg.role\":\n\tFormation\x12\r\n\x05order\x18\x01 \x01(\r\x12\x0e\n\x06heroid\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\r*]\n\x0b\x43hatChannel\x12\x0b\n\x07Invalid\x10\x00\x12\t\n\x05World\x10\x01\x12\x08\n\x04Zone\x10\x02\x12\t\n\x05Guild\x10\x03\x12\x08\n\x04Team\x10\x04\x12\x0b\n\x07Whisper\x10\x05\x12\n\n\x06System\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'roletype_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHATCHANNEL._serialized_start=88
  _CHATCHANNEL._serialized_end=181
  _FORMATION._serialized_start=28
  _FORMATION._serialized_end=86
# @@protoc_insertion_point(module_scope)
